server.port=8080
spring.application.name=api-gateway

# Config Server connection
spring.config.import=optional:configserver:http://localhost:8888

# Eureka Client
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Gateway Routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Custom Routes
spring.cloud.gateway.routes[0].id=labour-service
spring.cloud.gateway.routes[0].uri=lb://labour-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/labours/**

spring.cloud.gateway.routes[1].id=bus-service
spring.cloud.gateway.routes[1].uri=lb://bus-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/buses/**

spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://booking-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/bookings/**
